version: '1'
services:
    url_red:
        container_name: url_red
        image: redis:latest
        env_file:
            - .env
        volumes:
            - url_red:/data
        networks:
            - url_net
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 1s
            timeout: 3s
            retries: 5
        restart: always

    url_fastapi:
        container_name: url_fastapi
        build:
            context: ./app
        ports:
          - 80:80
        env_file:
            - .env
        networks:
            - url_net
        depends_on:
            - url_red
        restart: always

volumes:
    url_red:
        name: url_red

networks:
    url_net:
        name: url_net
        external: true
